### ISSUE TITLE
Help with numpy

### ISSUE THREAD

**Issue by jstarsky** [numpy/numpy-refactor#3]
Hello i want some help about how to install numpy in ironpython. I was looking in the site http://www.enthought.com/repo/.iron/. but the link is dead. can somebody help. thanks

**Comment by HarelM** [comment]
Not sure how relevant this is any more but the link isn't dead but you need to sign up to enthought:
https://www.enthought.com/
I'm trying to make it work with IronPython 2.7.5, I'm not sure I managed to make it work properly...
