### ISSUE TITLE
Can we archive this repo?

### ISSUE THREAD

**Issue by mattip** [numpy/numpy-refactor#5]
We should mark the README of this repo that it is of historical interest only, any suggestions for a suitable blurb?

**Comment by rgommers** [comment]
I've updated the repo description to say `INACTIVE - abandoned refactoring effort`.

I'd prefer not to update the README, as that bumps the repo right back up to the repository overview (https://github.com/numpy)

**Comment by SteveUM** [comment]
Just an FYI on this. I have been looking into the feasibility of resurrecting this project to allow Numpy access in Iron Python. I've been able to build all but the FFT lib in VS 2017 and get it to work on Iron Python 2.7.7. I may continue to dabble with this, but can keep my changes separate.

**Comment by rgommers** [comment]
Thanks for the update @SteveUM, interesting.

>  I've been able to build all but the FFT lib in VS 2017 

https://github.com/numpy/numpy/pull/11888 will probably fix that, replaces the whole fft library.

> I may continue to dabble with this, but can keep my changes separate.

What NumPy version did you base your work on, what's in this repo or something more recent?

**Comment by SteveUM** [comment]
@rgommers - I built based on what was in the repo, I made no changes. So I have no idea what numpy version it used (I didn't even look, probably and old one.) The only modifications made were to get it to build in Visual Studio 2017 (e.g. change reference .net reference libraries, etc.) There was a lot of work done on this and it seems a shame if no one uses it.

I'll take a look at the numpy/numpy#11888 is you mentioned.

**Comment by mattip** [comment]
Maybe we could port those changes to the numpy/numpy repo. Where is the work being done?

**Comment by SteveUM** [comment]
I am investigating this in my personal time which means, most likely, not much will get done.

**Comment by rgommers** [comment]
> I built based on what was in the repo, I made no changes. So I have no idea what numpy version it used (I didn't even look, probably and old one.)

It's based on NumPy 1.5 (from 2010).

> Maybe we could port those changes to the numpy/numpy repo. 

As far as I know, there's no interest anymore in this repo. IronPython isn't really a thing anymore, and there never even was an IronPython release for Python 3.x, so not much to see here.

**Comment by SteveUM** [comment]
> As far as I know, there's no interest anymore in this repo. IronPython isn't really a thing anymore, and there never even was an IronPython release for Python 3.x, so not much to see here.

Actually, the IronPython team, although small, is very active. They have made a few releases (2.7.x) within the last year or two and have now focused on support for Python 3.

My original note was just an FYI. If anything does happen with this I will (or others) will try to keep you informed. Thanks.

**Comment by rgommers** [comment]
@SteveUM thanks, good to know that a 3.x IronPython is coming!

> My original note was just an FYI. 

Yep, I got that. Thanks for the update!
